version: '3.8'

services:
  dify_chat_ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dify_chat_ui
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env:ro
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/auth_db
    networks:
      - dify_network
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: dify_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    networks:
      - dify_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: dify_pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - dify_network
    depends_on:
      - postgres

networks:
  dify_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
